on:
  workflow_dispatch:
    inputs:
      hash:
        description: 'WebRTC hash'
        required: true
jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=$PATH:${PWD}/depot_tools
          
          fetch --nohooks webrtc_ios
          
          cd src
          
          git checkout ${{ github.event.inputs.hash }}
          
          gclient sync

          gn gen ../out/mac_x64 --args='target_os="mac" target_cpu="x64" is_component_build=false is_debug=false rtc_libvpx_build_vp9=false enable_stripping=true rtc_enable_protobuf=false'

          gn gen ../out/ios_arm64 --args='target_os="ios" target_cpu="arm64" is_component_build=false use_xcode_clang=true is_debug=false  ios_deployment_target="10.0" rtc_libvpx_build_vp9=false use_goma=false ios_enable_code_signing=false enable_stripping=true rtc_enable_protobuf=false enable_ios_bitcode=false treat_warnings_as_errors=false'

          gn gen ../out/ios_x64 --args='target_os="ios" target_cpu="x64" is_component_build=false use_xcode_clang=true is_debug=true ios_deployment_target="10.0" rtc_libvpx_build_vp9=false use_goma=false ios_enable_code_signing=false enable_stripping=true rtc_enable_protobuf=false enable_ios_bitcode=false treat_warnings_as_errors=false'

          ninja -C ../out/mac_x64 sdk:mac_framework_objc
          ninja -C ../out/ios_arm64 sdk:framework_objc
          ninja -C ../out/ios_x64 sdk:framework_objc

          xcodebuild -create-xcframework \
            -framework ../out/ios_arm64/WebRTC.framework \
            -framework ../out/ios_x64/WebRTC.framework \
            -framework ../out/mac_x64/WebRTC.framework \
            -output ../out/WebRTC.xcframework

          cd ../out

          git init
          git remote add origin https://github.com/hamermike/webrtc.git
          git pull origin main

          git checkout -b release/${{ github.event.inputs.hash }}
          git add WebRTC.xcframework
          git commit -m "WebRTC Release ${{ github.event.inputs.hash }}" -- WebRTC.xcframework
          git push --set-upstream origin "release/${{ github.event.inputs.hash }}"
