on:
  workflow_dispatch:
    inputs:
      hash:
        description: 'WebRTC hash'
        required: true
jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=$PATH:${PWD}/depot_tools
          
          fetch --nohooks webrtc_ios
          
          cd src
          
          git checkout ${{ github.event.inputs.hash }}
          
          gclient sync

          gn gen ../out/mac_x64 --args='target_os="mac" target_cpu="x64" is_component_build=false is_debug=false rtc_libvpx_build_vp9=false enable_stripping=true rtc_enable_protobuf=false'

          ninja -C ../out/mac_x64 sdk:mac_framework_objc

          xcodebuild -create-xcframework \
            -framework ../out/mac_x64/WebRTC.framework \
            -output ../out/WebRTC.xcframework

          cd ../out

          echo "Initializing repo..."

          git init
          git remote add origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/hamermike/webrtc.git"
          git pull origin main

          echo "Checking out branch..."

          git checkout -b release/${{ github.event.inputs.hash }}
          git add WebRTC.xcframework
          git commit -m "WebRTC Release ${{ github.event.inputs.hash }}" -- WebRTC.xcframework
          git push --set-upstream origin "release/${{ github.event.inputs.hash }}"
